services:
  frontend:
    image: ghcr.io/a-marbach/conduit-frontend:${FRONTEND_VERSION:-latest}
    ports:
      - "8282:80"
    volumes:
      - frontend_data:/app/data   
    restart: on-failure

  backend:
    image: ghcr.io/a-marbach/conduit-backend:${BACKEND_VERSION:-latest}
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app/data    
    restart: on-failure
    env_file:
      - ./backend/.env

volumes:
  frontend_data:
  backend_data:
